export const products = [
  {
    slug: 'what-would-you-do',
    name: 'What Would You Do? 12 School Leadership Scenarios',
    category: 'School leadership',
    audience: 'Principals, aspiring leaders, and leadership teams',
    price: 19,
    thumbnail: '/products/scenarios-thumb.webp',
    cover: '/products/scenarios-cover.webp',
    checkout: 'https://drrobfurman.gumroad.com/l/wdenp',
    summary: 'Twelve school dilemmas that ask you to make the call before seeing how I handled it.',
    intro: 'A false sick note. A look-alike weapon on a bus. A request to move a child with significant behavior needs to another classroom. Practice the judgment behind the decision, then compare your approach with mine.',
    includes: [
      'A 26-page deck with twelve composite scenarios and my response to each',
      'A print-ready PDF and editable PowerPoint deck',
      'A facilitator guide with a 20-minute meeting plan, scenario index, and reflection sheet',
    ],
    usefulFor: ['Leadership team meetings', 'Aspiring administrator preparation', 'Individual reflection before a hard call'],
    note: 'The cases are composites with details changed to protect privacy. Follow your own laws, policy, reporting duties, and safety procedures.',
    license: 'One purchase covers internal professional learning at one school, including presenting to staff and copying the reflection page for participants. District or multi-school use needs a separate license.',
    related: '/resources/difficult-conversations-prep-kit',
    relatedLabel: 'Pair it with the Difficult Conversations Prep Kit',
  },
  {
    slug: 'principal-ai-starter-kit',
    name: 'Principal AI Starter Kit',
    category: 'AI for school leaders',
    audience: 'Principals, assistant principals, and school leadership teams',
    price: 29,
    thumbnail: '/products/principal-ai-thumb.webp',
    cover: '/products/principal-ai-cover.webp',
    checkout: 'https://drrobfurman.gumroad.com/l/principal_ai_kit',
    summary: 'A practical starting system for using AI in school leadership with privacy and judgment intact.',
    intro: 'Choose one useful AI workflow, try it with your team, and measure whether the work improves. The kit turns common leadership tasks into repeatable practices while keeping decisions with people.',
    includes: [
      'A quick-start guide, AI readiness audit, and prompt builder',
      '24 prompts for communication, meetings, instruction, operations, and leadership',
      'A staff meeting kit, 30-day implementation plan, communication templates, and scorecard',
      'A worked first-pilot example with a filled prompt, principal review, corrected agenda, and seven-day check',
      'Print-ready PDF and editable DOCX files',
    ],
    usefulFor: ['Starting responsible AI use', 'Preparing a staff discussion', 'Testing one measurable leadership workflow'],
    note: 'Use school-approved tools and keep confidential student and personnel information out of unapproved systems.',
    license: 'The purchase covers one school or one professional practice. Contact Dr. Rob for district or broader licensing.',
    related: '/ai-in-education',
    relatedLabel: 'Read the free AI in Education guide',
  },
  {
    slug: 'difficult-conversations-prep-kit',
    name: 'Difficult Conversations Prep Kit',
    category: 'School leadership',
    audience: 'Principals, deans, instructional leaders, and aspiring administrators',
    price: 12,
    thumbnail: '/products/conversations-thumb.webp',
    cover: '/products/conversations-cover.webp',
    checkout: 'https://drrobfurman.gumroad.com/l/difficultconversationsprepkit',
    summary: 'Prepare for a tense parent, staff, or colleague conversation without losing the human connection.',
    intro: 'Before the meeting, separate facts from assumptions, decide what must be said, and plan a responsible next step. The kit gives you a short preparation process rather than a script to read at someone.',
    includes: [
      'An 11-page printable PDF and editable Word version',
      'A Five-Minute Reset and Facts Before Friction worksheet',
      'A five-step Conversation Map and language for tense moments',
      'Three school scenarios, judgment practice, and an after-meeting debrief',
    ],
    usefulFor: ['Parent meetings', 'Staff accountability conversations', 'Explaining a difficult decision'],
    note: 'The preparation tools support your judgment and professional responsibilities. They do not decide the outcome of a real case.',
    license: 'Use the purchased materials for your professional practice. Contact Dr. Rob for broader school or district use.',
    related: '/resources/what-would-you-do',
    relatedLabel: 'Explore the 12-scenario leadership deck',
  },
  {
    slug: 'music-ai-creativity-bundle',
    name: 'Music + AI Creativity Bundle',
    category: 'Classroom creativity',
    audience: 'Grades 6–8 music and creative arts teachers',
    price: 19,
    thumbnail: '/products/music-ai-thumb.webp',
    cover: '/products/music-ai-cover.webp',
    checkout: 'https://drrobfurman.gumroad.com/l/MusicAICreativityBundle',
    summary: 'A grades 6–8 songwriting unit where students remain the authors and AI stays optional.',
    intro: 'Students plan a song, write original lyrics, revise their work, make musical choices, and explain why those choices matter. Run the unit with a school-approved AI music tool or without AI at all.',
    includes: [
      'A 15-page teacher guide and reproducible student workbook',
      'A flexible seven-day unit and expanded ten-day path',
      'Song design, style, chorus, and verse worksheets',
      'A project rubric, artist statement, AI prompt builder, and editable Word version',
    ],
    usefulFor: ['Songwriting units', 'Creative choice and revision', 'Discussing responsible AI in music'],
    note: 'Students remain the authors. The bundle includes a non-AI alternative, and any AI use stays teacher controlled.',
    license: 'One purchaser may print and use the materials in one school or professional practice. A school purchaser may share files with employees at that school; district distribution needs written permission.',
    related: '/ai-literacy-for-students',
    relatedLabel: 'Read the free AI literacy lesson',
  },
];

export function getProduct(slug) {
  return products.find((product) => product.slug === slug);
}
