'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import HumanEquationNav from '../../../components/HumanEquationNav';
import { addFactorImpact, createEvidenceEvent, saveEvidenceEvent } from '../../dashboard/evidenceModel';
const LEGACY_EVIDENCE_KEY='humanEquationEvidence';
const COURSE_PROGRESS_KEY='humanAwarenessCourseProgress';
const sections=[['What Human Awareness actually is','signal'],['What pressure does to interpretation','risk'],['What others experience from high vs low awareness','relational'],['Distortion patterns','risk'],['Recovery patterns','recovery'],['Leadership examples','signal'],['Reflection calibration','relational']];
const interactions=[{id:'scenario',prompt:'An AP enters escalated after a parent accusation. First move?',options:['Clarify timeline','Stabilize emotion','Check policy exposure','Escalate risk']},{id:'frame',prompt:'A teacher\'s abrupt tone most likely signals:',options:['Disrespect','Stress + unmet need','Resistance','Unprofessionalism']},{id:'pace',prompt:'When urgency rises:',options:['Interpret then act','Brief inquiry then act','Deep inquiry then act']}];
const sims=[{id:'sim1',title:'Micro-Pressure 01',prompt:'Teacher enters escalated after parent complaint. What do you notice FIRST?',choices:['Procedural concern','Emotional state','Policy issue','Timeline risk']},{id:'sim2',title:'Micro-Pressure 02',prompt:'Tense staff meeting goes silent. Interpret first:',choices:['Compliance achieved','Unspoken disagreement','Execution confusion','Fear of speaking']},{id:'sim3',title:'Micro-Pressure 03',prompt:'Student conflict video spreads online. First attention:',choices:['Reputation risk','Family emotional climate','Procedural review','Staff psychological safety']}];
const reflections=['What urgency changes your interpretation speed most?','When do people misunderstand your intent most?','Do you prioritize emotional stabilization or clarity first?','What leadership feedback has surprised you?'];
export default function Page(){
 const [answers,setAnswers]=useState({}); const [refs,setRefs]=useState({}); const [done,setDone]=useState(false);
 const total=interactions.length+sims.length; const answered=[...interactions,...sims].filter(q=>answers[q.id]!==undefined).length; const refCount=Object.values(refs).filter(Boolean).length; const progress=Math.round(((answered+refCount)/(total+reflections.length))*100);
 const tendency=useMemo(()=>{const emo=['Stabilize emotion','Stress + unmet need','Brief inquiry then act'];let hits=0;interactions.forEach(i=>{const idx=answers[i.id]; if(idx!==undefined && emo.includes(i.options[idx])) hits++;});return hits>=2?'Context-first':'Action-first';},[answers]);
 const score=Math.max(2.3,Math.min(4.8,+(2.7+answered*.18+refCount*.12).toFixed(2))); const confidence=Math.min(98,28+answered*12+refCount*8); const ready=answered===total&&refCount>=3;
 const save=()=>{if(typeof window==='undefined')return; const payload={type:'HUMAN_AWARENESS_COURSE',completedAt:new Date().toISOString(),progress,score,confidence,tendency,answers,refs};
  const legacy=JSON.parse(localStorage.getItem(LEGACY_EVIDENCE_KEY)||'[]'); localStorage.setItem(LEGACY_EVIDENCE_KEY,JSON.stringify([...legacy,payload])); localStorage.setItem(COURSE_PROGRESS_KEY,JSON.stringify({complete:true,...payload}));
  saveEvidenceEvent(createEvidenceEvent({sourceType:'course_reflection',sourceId:`human-awareness-${Date.now()}`,sourceLabel:'Human Awareness Course Module',evidenceType:'HUMAN_AWARENESS_COURSE',summary:`Course completed with ${confidence}% confidence evidence.`,tags:['human awareness','course'],factorImpacts:[addFactorImpact('humanAwareness',(score-3)/1.4,Math.min(.95,confidence/100),score>=3.5?'positive':'risk','Course calibration evidence'),addFactorImpact('regulationUnderPressure',tendency==='Context-first'?.25:-.1,.68,tendency==='Context-first'?'positive':'risk','Pacing signal'),addFactorImpact('trustConstruction',refCount>=3?.2:.05,.65,'positive','Reflection intelligence')],weight:.95})); setDone(true);
 };
 return <main className='section section-light hes-awareness-page'><div className='container'><HumanEquationNav/>
 <section className='hes-awareness-hero top-space-sm'><div className='hes-awareness-glow'/><div className='hes-awareness-glow alt'/><p className='eyebrow'>Premium Factor Module</p><h1>Human Awareness</h1><h2>“Pressure changes what humans notice first.”</h2><p>This factor explores how leaders interpret emotion, context, urgency, and relational meaning under pressure.</p><div className='hes-awareness-live'><div><label>Human Awareness score</label><strong>{score} / 5</strong></div><div><label>Confidence growth</label><strong>{confidence}%</strong></div><div><label>Interpretation tendency</label><strong>{tendency}</strong></div><div className='ring' style={{'--ring':`${Math.min(360,progress*3.6)}deg`}}><span>{progress}%</span></div></div></section>
 <section className='hes-awareness-grid top-space-sm'>{sections.map(([title,t])=><article key={title} className={`hes-awareness-card ${t}`}><h3>{title}</h3></article>)}</section>
 <section className='top-space-sm card'><h2>Calibration Moments</h2>{interactions.map(i=><article key={i.id} className='hes-choice-block'><h4>{i.prompt}</h4><div className='button-grid top-space-sm'>{i.options.map((o,idx)=><button key={o} className={`button ${answers[i.id]===idx?'primary':'secondary'}`} onClick={()=>setAnswers(p=>({...p,[i.id]:idx}))}>{o}</button>)}</div></article>)}</section>
 <section className='top-space-sm card'><h2>Micro-Pressure Moments</h2><div className='hes-awareness-grid'>{sims.map(s=>{const p=answers[s.id];return <article key={s.id} className='hes-awareness-card signal'><p className='eyebrow'>{s.title}</p><h3>{s.prompt}</h3><div className='button-grid top-space-sm'>{s.choices.map((c,idx)=><button key={c} className={`button ${p===idx?'primary':'secondary'}`} onClick={()=>setAnswers(pr=>({...pr,[s.id]:idx}))}>{c}</button>)}</div>{p!==undefined&&<p className='top-space-sm'><strong>Signal:</strong> {['structure-first','emotion-first','policy-first','risk-first'][p]} orientation under pressure.</p>}</article>})}</div></section>
 <section className='top-space-sm card'><h2>Leadership Reflection Calibration</h2>{reflections.map((q,idx)=><label key={q} className='hes-reflect-field'><span>{idx+1}. {q}</span><textarea rows={3} value={refs[idx]||''} onChange={e=>setRefs(p=>({...p,[idx]:e.target.value}))}/></label>)}</section>
 <section className='top-space-sm card'><h2>Human Awareness Debrief</h2><p>Strongest observed tendency: <strong>{tendency}</strong>.</p><p>Likely pressure drift: <strong>{tendency==='Context-first'?'Urgency compression risk':'Interpretation narrowing risk'}</strong>.</p><div className='button-row top-space-sm'><button className='button primary' disabled={!ready||done} onClick={save}>{done?'Evidence Saved to Dashboard':'Complete Module + Sync Dashboard Evidence'}</button><Link href='/human-equation-suite/dashboard' className='button secondary'>Open Dashboard</Link></div></section>
 </div></main>;
}
