import { createEmptyMasterProfile, dimensionDefinitions } from './profileData';

const sourceKeys = ['diagnostic', 'parentCall', 'leadershipSim', 'urbanSim', 'observationLab'];
const sourceLabelMap = { diagnostic: 'Leadership Diagnostic', parentCall: 'Parent Call Rehearsal', leadershipSim: 'Leadership Simulation', urbanSim: 'Urban Student Simulation', observationLab: 'Observation Lab' };

const c = (diagnostic, simulation) => ({ diagnostic, parentCall: simulation, leadershipSim: simulation, urbanSim: simulation, observationLab: simulation });
const makeDimension = (score, baseline, simulation, strongestEvidenceSource, growthNote, trend = 'Mixed under pressure contexts.', confidence = 'moderate') => ({ blendedCompositeScore: score, baselineDiagnosticScore: baseline, simulationEvidenceScore: simulation, confidence, trend, strongestEvidenceSource, growthNote, statusProgress: Math.round((score / 5) * 100), evidenceWeights: c(0.5, 0.5), history: [] });

const buildDimensions = (scores, strongestEvidenceSource, growthNote) => Object.fromEntries(dimensionDefinitions.map(({ key, label }) => [key, { label, ...makeDimension(scores[key], scores[key] + 0.2 > 5 ? 5 : +(scores[key] + 0.2).toFixed(1), scores[key] - 0.2 < 0 ? 0 : +(scores[key] - 0.2).toFixed(1), strongestEvidenceSource, growthNote) }]));

const buildProfile = ({ key, label, scores, distortions, strongestDimensions, growthEdges, growthNotes, timelineEvents, confidenceLevels, trends, strongestEvidenceSource, growthNote }) => {
  const base = createEmptyMasterProfile();
  base.dimensions = { ...base.dimensions, ...buildDimensions(scores, strongestEvidenceSource, growthNote) };
  sourceKeys.forEach((sourceKey, index) => {
    const completion = 62 + (index * 8);
    base.evidenceSources[sourceKey] = { ...base.evidenceSources[sourceKey], status: completion > 90 ? 'completed' : 'in_progress', completion, contribution: `${sourceLabelMap[sourceKey]} contributes weighted evidence into the unified dimension blend.`, latestUpdate: new Date(Date.now() - (index * 86400000)).toLocaleDateString('en-US') };
  });
  base.profileVersion = 2;
  base.generatedAt = new Date().toISOString();
  base.profileTitle = `${label} Dev Evidence Profile`;
  base.confidenceLevels = confidenceLevels;
  base.distortions = distortions;
  base.trends = trends;
  base.simulationHistory = timelineEvents.map((event) => ({ ...event, status: 'completed' }));
  base.strongestDimensions = strongestDimensions;
  base.growthEdges = growthEdges;
  base.growthNotes = growthNotes;
  base.interpretation = { summary: `${label} profile blends baseline diagnostics with simulated pressure evidence for rapid dashboard testing.`, confidenceNarrative: 'Behavioral confidence remains early because live-pressure simulations are still limited in variety and repetition.' };
  return { key, label, profile: base };
};

export const DEV_PROFILE_PRESETS = [
  buildProfile({ key: 'harmonizer', label: 'Harmonizer', strongestEvidenceSource: 'Parent Call Rehearsal', growthNote: 'Balance empathy with firmer boundary-setting.', confidenceLevels: { baseline: 0.72, blended: 0.76 }, strongestDimensions: ['Human Awareness', 'Trust Construction'], growthEdges: ['Regulation Under Pressure', 'Reality Anchoring'], growthNotes: ['Practice concise boundary language.', 'Use clearer accountability checkpoints.'], trends: { overall: 'Relationally strong with occasional conflict-avoidance.', trajectory: 'Improving directness under stress.' }, distortions: { emerging: ['Approval-seeking can delay direct correction.'], observed: ['Conflict smoothing appears under interpersonal pressure.'], mild: ['Softening language reduces urgency.'], needsMoreEvidence: ['Behavioral confidence remains early because escalation-scenario evidence is still limited.'] }, timelineEvents: [{ source: 'Leadership Diagnostic', completedAt: '2026-05-12T14:00:00Z' }, { source: 'Parent Call Rehearsal', completedAt: '2026-05-16T18:20:00Z' }], scores: { regulationUnderPressure: 3.1, humanAwareness: 4.4, trustConstruction: 4.2, realityAnchoring: 3.0, grayAreaLeadership: 3.6, teamSystemsLeadership: 3.5, instructionalAcademicLeadership: 3.7, visionChangeLeadership: 3.8 } }),
  buildProfile({ key: 'controller', label: 'Controller', strongestEvidenceSource: 'Leadership Simulation', growthNote: 'Increase listening and distributed ownership.', confidenceLevels: { baseline: 0.69, blended: 0.82 }, strongestDimensions: ['Reality Anchoring', 'Team & Systems Leadership'], growthEdges: ['Human Awareness', 'Trust Construction'], growthNotes: ['Lead with inquiry before directives.', 'Delegate with clear guardrails.'], trends: { overall: 'Execution-first profile with control reflexes.', trajectory: 'Can improve by building trust loops.' }, distortions: { emerging: ['Control narrows perspective under challenge.'], observed: ['Directive overreach in pressured conversations.'], mild: ['Defensiveness when authority is questioned.'], needsMoreEvidence: ['Behavioral confidence remains early because cross-cultural evidence is narrow.'] }, timelineEvents: [{ source: 'Leadership Diagnostic', completedAt: '2026-04-25T10:00:00Z' }, { source: 'Leadership Simulation', completedAt: '2026-05-03T09:30:00Z' }], scores: { regulationUnderPressure: 3.4, humanAwareness: 2.4, trustConstruction: 2.5, realityAnchoring: 4.2, grayAreaLeadership: 3.1, teamSystemsLeadership: 4.1, instructionalAcademicLeadership: 3.8, visionChangeLeadership: 3.2 } }),
  buildProfile({ key: 'martyr', label: 'Martyr', strongestEvidenceSource: 'Urban Student Simulation', growthNote: 'Replace over-functioning with system ownership.', confidenceLevels: { baseline: 0.63, blended: 0.71 }, strongestDimensions: ['Human Awareness', 'Instructional & Academic Leadership'], growthEdges: ['Team & Systems Leadership', 'Regulation Under Pressure'], growthNotes: ['Rebuild boundaries through delegation rituals.', 'Use team routines instead of personal rescue.'], trends: { overall: 'Service-driven with burnout risk pattern.', trajectory: 'Needs stamina safeguards.' }, distortions: { emerging: ['Over-functioning replaces team accountability.'], observed: ['Stress language signals depletion in debriefs.'], mild: ['Rescue pattern limits systemic problem-solving.'], needsMoreEvidence: ['Behavioral confidence remains early because long-horizon stamina evidence is limited.'] }, timelineEvents: [{ source: 'Leadership Diagnostic', completedAt: '2026-03-18T11:00:00Z' }, { source: 'Urban Student Simulation', completedAt: '2026-05-11T13:45:00Z' }], scores: { regulationUnderPressure: 2.7, humanAwareness: 4.3, trustConstruction: 3.6, realityAnchoring: 3.2, grayAreaLeadership: 3.1, teamSystemsLeadership: 2.6, instructionalAcademicLeadership: 3.9, visionChangeLeadership: 3.2 } }),
  buildProfile({ key: 'performer', label: 'Performer', strongestEvidenceSource: 'Leadership Simulation', growthNote: 'Anchor narrative strength with evidence discipline.', confidenceLevels: { baseline: 0.74, blended: 0.79 }, strongestDimensions: ['Vision & Change Leadership', 'Trust Construction'], growthEdges: ['Reality Anchoring', 'Gray Area Leadership'], growthNotes: ['Use evidence logs before strategic storytelling.', 'Name uncertainty explicitly in high-stakes moments.'], trends: { overall: 'Charismatic style with uneven execution depth.', trajectory: 'Stabilizes through data-first habits.' }, distortions: { emerging: ['Image management can outrun transparency.'], observed: ['Narrative inflation after hard feedback.'], mild: ['Short-term wins overshadow root-cause fixes.'], needsMoreEvidence: ['Behavioral confidence remains early because contradiction-rich scenarios are sparse.'] }, timelineEvents: [{ source: 'Leadership Diagnostic', completedAt: '2026-02-14T15:00:00Z' }, { source: 'Leadership Simulation', completedAt: '2026-05-07T08:30:00Z' }], scores: { regulationUnderPressure: 3.2, humanAwareness: 3.8, trustConstruction: 4.1, realityAnchoring: 2.8, grayAreaLeadership: 2.9, teamSystemsLeadership: 3.3, instructionalAcademicLeadership: 3.5, visionChangeLeadership: 4.4 } }),
  buildProfile({ key: 'systems-operator', label: 'Systems Operator', strongestEvidenceSource: 'Observation Lab', growthNote: 'Blend process excellence with relational leadership.', confidenceLevels: { baseline: 0.77, blended: 0.84 }, strongestDimensions: ['Team & Systems Leadership', 'Reality Anchoring'], growthEdges: ['Human Awareness', 'Vision & Change Leadership'], growthNotes: ['Add emotional check-ins to execution cycles.', 'Translate operations into shared purpose narratives.'], trends: { overall: 'Operationally consistent and disciplined.', trajectory: 'Needs broader relational adaptation.' }, distortions: { emerging: ['Process fidelity can reduce adaptive empathy.'], observed: ['Rigid sequencing in fluid scenarios.'], mild: ['Low inspirational narrative during change.'], needsMoreEvidence: ['Behavioral confidence remains early because transformational scenarios are limited.'] }, timelineEvents: [{ source: 'Leadership Diagnostic', completedAt: '2026-01-29T17:00:00Z' }, { source: 'Observation Lab', completedAt: '2026-04-29T11:30:00Z' }], scores: { regulationUnderPressure: 3.9, humanAwareness: 2.9, trustConstruction: 3.1, realityAnchoring: 4.3, grayAreaLeadership: 3.7, teamSystemsLeadership: 4.5, instructionalAcademicLeadership: 3.8, visionChangeLeadership: 3.0 } }),
  buildProfile({ key: 'visionary', label: 'Visionary', strongestEvidenceSource: 'Leadership Simulation', growthNote: 'Convert strategic imagination into stable execution loops.', confidenceLevels: { baseline: 0.68, blended: 0.75 }, strongestDimensions: ['Vision & Change Leadership', 'Gray Area Leadership'], growthEdges: ['Regulation Under Pressure', 'Instructional & Academic Leadership'], growthNotes: ['Use 30-day implementation commitments.', 'Strengthen regulation before major pivots.'], trends: { overall: 'Bold future orientation with variable grounding.', trajectory: 'High upside when execution discipline improves.' }, distortions: { emerging: ['Future-focus can bypass near-term constraints.'], observed: ['Pressure spikes increase impulsive pivots.'], mild: ['Execution details lag strategic intent.'], needsMoreEvidence: ['Behavioral confidence remains early because repeated implementation-cycle evidence is limited.'] }, timelineEvents: [{ source: 'Leadership Diagnostic', completedAt: '2026-03-08T12:00:00Z' }, { source: 'Leadership Simulation', completedAt: '2026-05-19T09:50:00Z' }], scores: { regulationUnderPressure: 2.9, humanAwareness: 3.4, trustConstruction: 3.5, realityAnchoring: 2.9, grayAreaLeadership: 4.1, teamSystemsLeadership: 3.2, instructionalAcademicLeadership: 2.8, visionChangeLeadership: 4.6 } }),
];
