export const guitarLicks = [
  {
    title: 'Porch Light Turnaround', key: 'A', style: 'Blues', difficulty: 'Beginner', tempo: '78 bpm', chord: 'A7', mood: 'Gritty', targetNotes: ['C# (3rd)', 'E (5th)', 'G (b7)'],
    tab: `e|------------------------|\nB|------5-8b9r8-5---------|\nG|--5/6-----------6-5-----|\nD|--------------------7---|\nA|------------------------|\nE|------------------------|`,
    why: 'The slide lands on the major 3rd, then the small bend touches the bluesy flat 7 color before resolving to the A7 root area.',
    steps: ['Say the chord out loud: A7.', 'Slide into fret 6 on the G string cleanly.', 'Make the 8th-fret bend small and vocal, not wide.', 'Loop the last three notes until the 7th fret on D feels like home.'],
  },
  {
    title: 'Midnight Shuffle Answer', key: 'E', style: 'Blues', difficulty: 'Beginner', tempo: '86 bpm', chord: 'E7', mood: 'Laid-back', targetNotes: ['G# (3rd)', 'D (b7)', 'E (root)'],
    tab: `e|----------------0-------|\nB|----------3-0-----------|\nG|------1/2-----2-0h1-----|\nD|--2-2----------------2--|\nA|------------------------|\nE|------------------------|`,
    why: 'It mixes open-string snap with the E7 third, giving a classic call-and-response phrase that sounds finished on low E.',
    steps: ['Keep the two D-string notes short like a shuffle pickup.', 'Let the open high E ring briefly.', 'Hammer 0h1 on G slowly so the G# speaks clearly.', 'Play it over one bar of E7 and leave space after it.'],
  },
  {
    title: 'Blue Door Rake', key: 'G', style: 'Blues', difficulty: 'Intermediate', tempo: '72 bpm', chord: 'G7', mood: 'Greasy', targetNotes: ['B (3rd)', 'F (b7)', 'G (root)'],
    tab: `e|------------------------|\nB|--6r5-3-----------------|\nG|--------5-3h4-----------|\nD|--------------5-3-------|\nA|------------------5-----|\nE|------------------------|`,
    why: 'The lick starts with a greasy release, then turns the minor third into the major third before dropping into the root.',
    steps: ['Pre-bend or slightly push the 6th fret before releasing.', 'Do not rush the 3h4 move; that is the blues-to-dominant sound.', 'Mute unused strings with both hands.', 'End firmly on the 5th fret of the A string.'],
  },
  {
    title: 'Garage Door Climb', key: 'E', style: 'Rock', difficulty: 'Beginner', tempo: '104 bpm', chord: 'E5', mood: 'Punchy', targetNotes: ['E (root)', 'G (b3)', 'B (5th)'],
    tab: `e|------------------------|\nB|------------------------|\nG|----------0-2-0---------|\nD|------0h2-------2-0-----|\nA|--0h2---------------2---|\nE|------------------------|`,
    why: 'Minor-pentatonic hammer-ons create momentum while the fifth and root keep it strong over a power chord.',
    steps: ['Use downstrokes on the first note of each string.', 'Keep hammer-ons even in volume.', 'Accent the 2nd fret on D as the high point.', 'Practice at half tempo before adding gain.'],
  },
  {
    title: 'Amp Glow Hook', key: 'D', style: 'Rock', difficulty: 'Intermediate', tempo: '118 bpm', chord: 'D5', mood: 'Anthemic', targetNotes: ['D (root)', 'F (b3)', 'A (5th)'],
    tab: `e|------------------------|\nB|--10-8------------------|\nG|-------9-7---7----------|\nD|-----------9---9-7------|\nA|-------------------10---|\nE|------------------------|`,
    why: 'A descending D minor pentatonic shape sounds like a hook because it repeats the 7th-fret G-string anchor before resolving low.',
    steps: ['Pick the first two notes with authority.', 'Let the 7th fret on G feel like a checkpoint.', 'Keep the descent tight and evenly spaced.', 'Try it after a D5 chord stab.'],
  },
  {
    title: 'Redline Bend', key: 'A', style: 'Rock', difficulty: 'Advanced', tempo: '128 bpm', chord: 'A5', mood: 'Aggressive', targetNotes: ['C (b3)', 'D (4th)', 'E (5th)'],
    tab: `e|------------------------|\nB|--8b10-8-5--------------|\nG|-----------7p5---5------|\nD|---------------7---7-5--|\nA|------------------------|\nE|------------------------|`,
    why: 'The big bend supplies the peak, and the pull-off run drops back into A minor pentatonic with a tough rock resolution.',
    steps: ['Check the bend pitch against fret 10 before looping.', 'Relax the hand after the bend release.', 'Pull off toward the floor for a clean 7p5.', 'Play it with a metronome on beats 2 and 4.'],
  },
  {
    title: 'Sunday Morning Thirds', key: 'C', style: 'Soulful Major', difficulty: 'Beginner', tempo: '76 bpm', chord: 'Cmaj7', mood: 'Warm', targetNotes: ['E (3rd)', 'G (5th)', 'B (7th)'],
    tab: `e|----------7-8-----------|\nB|------8-------8---------|\nG|--7/9---9-------9-7-----|\nD|--------------------10--|\nA|------------------------|\nE|------------------------|`,
    why: 'Major-scale notes outline the sweet 3rd and 7th of Cmaj7 without sounding like an exercise.',
    steps: ['Use a light touch and let notes breathe.', 'Slide into the 9th fret smoothly.', 'Make the high 8th fret sing rather than spike.', 'End on C at the 10th fret of D.'],
  },
  {
    title: 'Window Seat Melody', key: 'G', style: 'Soulful Major', difficulty: 'Intermediate', tempo: '82 bpm', chord: 'G6', mood: 'Reflective', targetNotes: ['B (3rd)', 'E (6th)', 'G (root)'],
    tab: `e|------------------------|\nB|--8-10-8----------------|\nG|---------9-7h9-7--------|\nD|-----------------9-7-5--|\nA|------------------------|\nE|------------------------|`,
    why: 'The 6th gives the phrase a warm R&B lift while the final descent settles back into the G chord family.',
    steps: ['Play legato first, then add picked accents.', 'Hear the 10th fret on B as the emotional peak.', 'Keep the 7h9 hammer-on relaxed.', 'Resolve gently, not aggressively.'],
  },
  {
    title: 'Gold Thread Resolve', key: 'F', style: 'Soulful Major', difficulty: 'Advanced', tempo: '70 bpm', chord: 'Fmaj9', mood: 'Shimmering', targetNotes: ['A (3rd)', 'G (9th)', 'C (5th)'],
    tab: `e|--8-10-12-10-8----------|\nB|--------------10-8------|\nG|-------------------10-9-|\nD|------------------------|\nA|------------------------|\nE|------------------------|`,
    why: 'The melody touches the 9th for shimmer, then resolves through chord tones instead of ending on a plain scale fragment.',
    steps: ['Use a warm clean tone or neck pickup.', 'Connect the top-string notes smoothly.', 'Let the 10th fret on B ring into the descent.', 'Practice with a slow Fmaj9 backing drone.'],
  },
  {
    title: 'Fence Post Pickup', key: 'G', style: 'Country-ish', difficulty: 'Beginner', tempo: '96 bpm', chord: 'G', mood: 'Bright', targetNotes: ['B (3rd)', 'D (5th)', 'G (root)'],
    tab: `e|----------3-------------|\nB|------3h5---5p3---------|\nG|--2/4-----------4-2-0---|\nD|------------------------|\nA|------------------------|\nE|------------------------|`,
    why: 'The major pentatonic slide and open-string-friendly ending give it a bright country vocabulary without needing speed.',
    steps: ['Use hybrid picking if comfortable, pick otherwise.', 'Snap the 3h5 lightly.', 'Let the open G finish the sentence.', 'Try it after a simple G-C-G rhythm figure.'],
  },
  {
    title: 'Dusty Double-Stop', key: 'D', style: 'Country-ish', difficulty: 'Intermediate', tempo: '108 bpm', chord: 'D', mood: 'Bouncy', targetNotes: ['F# (3rd)', 'A (5th)', 'D (root)'],
    tab: `e|--5-5---3-2-------------|\nB|--7-7---5-3-------------|\nG|--------------4-2-------|\nD|------------------4-0---|\nA|------------------------|\nE|------------------------|`,
    why: 'Double-stops state the D chord clearly, then the single-note tag walks down to an open-root landing.',
    steps: ['Pinch the first two string pairs together.', 'Keep the double-stops short and bouncy.', 'Do not overbend the country flavor; this one is clean.', 'Land the open D in time.'],
  },
  {
    title: 'Pickup Truck Chime', key: 'A', style: 'Country-ish', difficulty: 'Advanced', tempo: '116 bpm', chord: 'A', mood: 'Snappy', targetNotes: ['C# (3rd)', 'E (5th)', 'A (root)'],
    tab: `e|--9-5-------------------|\nB|------7-5---------------|\nG|----------6-4h6-4-------|\nD|------------------7-4---|\nA|----------------------7-|\nE|------------------------|`,
    why: 'The wide top-string skip sounds like a country chime, then the line spells A major pentatonic back to a sturdy root.',
    steps: ['Practice the first string skip alone.', 'Use pick-and-fingers for extra snap if possible.', 'Keep the 4h6 hammer-on bright and in time.', 'Loop slowly until every string change is clean.'],
  },

  {
    title: 'River Bend Reply', key: 'C', style: 'Blues', difficulty: 'Easy', tempo: '82 bpm', chord: 'C7', mood: 'Smoky', targetNotes: ['E (3rd)', 'Bb (b7)', 'C (root)'],
    tab: `e|------------------------|\nB|------8-11b12-8---------|\nG|--8/9----------9-8------|\nD|-------------------10---|\nA|------------------------|\nE|------------------------|`,
    why: 'The phrase leans into the C7 third, then answers with a compact blues bend that resolves to the chord root area.',
    steps: ['Slide into E with confidence.', 'Keep the bend narrow and vocal.', 'Let the 8th fret on B breathe for a beat.', 'Resolve to the 10th fret on D without rushing.'],
  },
  {
    title: 'Delta Door Knock', key: 'D', style: 'Blues', difficulty: 'Intermediate', tempo: '90 bpm', chord: 'D7', mood: 'Raw', targetNotes: ['F# (3rd)', 'C (b7)', 'D (root)'],
    tab: `e|------------------------|\nB|--13r10-----------------|\nG|--------12-10h11--------|\nD|----------------12-10---|\nA|---------------------12-|\nE|------------------------|`,
    why: 'The release gives the lick a vocal blues entrance while the half-step hammer-on spells the dominant chord sound.',
    steps: ['Hear the bend release before picking it.', 'Make 10h11 on G the chord-tone moment.', 'Mute around the descending line.', 'Finish with a sturdy D root on the A string.'],
  },
  {
    title: 'Backbeat Spark', key: 'C', style: 'Rock', difficulty: 'Easy', tempo: '112 bpm', chord: 'C5', mood: 'Driving', targetNotes: ['C (root)', 'Eb (b3)', 'G (5th)'],
    tab: `e|------------------------|\nB|------------------------|\nG|------3-5-3-------------|\nD|--3h5-------5-3---------|\nA|----------------5-3-----|\nE|--------------------6---|`,
    why: 'A tight minor-pentatonic cell climbs and snaps back, giving a useful rock response over a C power chord.',
    steps: ['Keep the hammer-on punchy.', 'Accent the 5th fret on G.', 'Palm mute the lower-string ending lightly.', 'Loop it with a C5 backbeat.'],
  },
  {
    title: 'Stadium Step Down', key: 'G', style: 'Rock', difficulty: 'Intermediate', tempo: '124 bpm', chord: 'G5', mood: 'Bold', targetNotes: ['G (root)', 'Bb (b3)', 'D (5th)'],
    tab: `e|------------------------|\nB|--15-13-----------------|\nG|--------15-12-----------|\nD|--------------15-12-----|\nA|-------------------13---|\nE|------------------------|`,
    why: 'Wide-position notes create a bigger rock sound while every landing point stays inside G minor pentatonic.',
    steps: ['Use alternate picking at a slow tempo.', 'Let the opening note sound like a hook.', 'Keep the string crossings relaxed.', 'End with a strong downstroke.'],
  },
  {
    title: 'Maple Street Glide', key: 'A', style: 'Soulful Major', difficulty: 'Easy', tempo: '74 bpm', chord: 'Amaj7', mood: 'Tender', targetNotes: ['C# (3rd)', 'F# (6th)', 'G# (7th)'],
    tab: `e|----------4-5-----------|\nB|------5-------5---------|\nG|--4/6---6-------6-4-----|\nD|--------------------7---|\nA|------------------------|\nE|------------------------|`,
    why: 'The major 6th and 7th add sweetness without making the line too busy for a slow groove.',
    steps: ['Use a clean tone.', 'Slide into C# smoothly.', 'Keep the top notes connected.', 'Resolve gently to A on the D string.'],
  },
  {
    title: 'Late Train Resolve', key: 'D', style: 'Soulful Major', difficulty: 'Intermediate', tempo: '80 bpm', chord: 'D6', mood: 'Hopeful', targetNotes: ['F# (3rd)', 'B (6th)', 'D (root)'],
    tab: `e|------------------------|\nB|--7-10-7----------------|\nG|---------9-7h9-7--------|\nD|-----------------9-7-4--|\nA|------------------------|\nE|------------------------|`,
    why: 'The sixth gives the phrase lift while the final D chord tone makes the melody feel complete.',
    steps: ['Sing the first three notes before playing.', 'Keep the hammer-on relaxed.', 'Do not over-accent the descent.', 'Land softly on the 4th fret of D.'],
  },
  {
    title: 'Front Porch Snap', key: 'C', style: 'Country-ish', difficulty: 'Easy', tempo: '100 bpm', chord: 'C', mood: 'Cheerful', targetNotes: ['E (3rd)', 'G (5th)', 'C (root)'],
    tab: `e|----------8-------------|\nB|------8h10--10p8--------|\nG|--7/9------------9-7----|\nD|---------------------10-|\nA|------------------------|\nE|------------------------|`,
    why: 'Major-pentatonic movement and a quick pull-off create a friendly country-pop lick in C.',
    steps: ['Try hybrid picking on the B string.', 'Keep the pull-off light.', 'Let the slide sound bright.', 'Resolve clearly to C.'],
  },
  {
    title: 'Barn Light Tag', key: 'E', style: 'Country-ish', difficulty: 'Intermediate', tempo: '112 bpm', chord: 'E', mood: 'Snappy', targetNotes: ['G# (3rd)', 'B (5th)', 'E (root)'],
    tab: `e|--12-9------------------|\nB|-------12-9-------------|\nG|------------11-9h11-9---|\nD|----------------------11|\nA|------------------------|\nE|------------------------|`,
    why: 'The high-string skip and quick hammer-on outline E major pentatonic with a crisp country finish.',
    steps: ['Pick the top note firmly.', 'Keep the string skip clean.', 'Snap the 9h11 hammer-on in time.', 'Try it after an E-A-E rhythm figure.'],
  },
];
